// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn4tYUaN6b_Ctp5360lGllmJLEdmPO34M',
    appId: '1:1078972267094:android:a83d71d619b48a779599f7',
    messagingSenderId: '1078972267094',
    projectId: 'lima-bd8f2',
    storageBucket: 'lima-bd8f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vzxFHGfGoS_1Cffkadmq6Iad-nFdjLs',
    appId: '1:1078972267094:ios:095258540f81173a9599f7',
    messagingSenderId: '1078972267094',
    projectId: 'lima-bd8f2',
    storageBucket: 'lima-bd8f2.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBht6ABDkMRiSgGkaFucheFXpBHc6r6j9M',
    appId: '1:1078972267094:web:4108c3addcb9f97b9599f7',
    messagingSenderId: '1078972267094',
    projectId: 'lima-bd8f2',
    authDomain: 'lima-bd8f2.firebaseapp.com',
    storageBucket: 'lima-bd8f2.firebasestorage.app',
    measurementId: 'G-LC33RRM3SB',
  );

}